#!/usr/bin/env node

/* jshint node:true */
'use strict';

var YamlParser = require('yamljs'),
	ejs = require('ejs');

var yamlInputFilepath,
	outputScriptName;

// parse input filename
yamlInputFilepath = process.argv[2];
if (!yamlInputFilepath || yamlInputFilepath === '' || yamlInputFilepath.indexOf('.yml') < 0) {
	console.log('Please specify an input file as parameter!', '...found', yamlInputFilepath);
	return;
}

outputScriptName = yamlInputFilepath.split('.yml')[0] + '.sh';
yamlInputFilepath = require('path').resolve('./', yamlInputFilepath);

// parse yaml file
var containerName2conf = YamlParser.load(yamlInputFilepath);

// read template
var template = require('fs').readFileSync(require('path').resolve(__dirname, './template-script.sh.ejs'), {
	encoding: 'utf8'
});

// transform parsed yaml into known and standard data structure
var images = [];
Object.keys(containerName2conf).forEach(function(containerName) {
	var image, containerConfiguration;

	containerConfiguration = containerName2conf[containerName];

	image = {
		containerName: containerName,
		name: containerConfiguration.image || null,
		ports: containerConfiguration.ports || [],
		environment: containerConfiguration.environment || [],
		volumes: containerConfiguration.volumes || [],
		command: containerConfiguration.command || null,
		build: containerConfiguration.build || null
	};

	image.volumes = image.volumes.map(function(vol) {
		var left, right, splitted;

		splitted = vol.split(/:/gi);
		left = splitted[0];
		right = splitted[1];

		return '$(pwd)/' + left + ':' + right;

	});

	images.push(image);

});

var output;

var helpers = {
	ports: function(image) {
		if (image.ports.length) {
			return image.ports.map(function(port) {
				return ' -p ' + port;
			}).join('');
		}
		return '';
	},
	env: function(image) {
		if (image.environment.length) {
			return image.environment.map(function(env) {
				return ' -e  ' + env;
			}).join(' ');
		}
		return '';
	},
	volumes: function(image) {
		if (image.volumes.length) {
			return image.volumes.map(function(vol) {
				return ' -v ' + vol;
			}).join(' ');
		}
	},
	cmd: function(image) {
		if (image.command) {
			return image.command;
		}
		return '';
	}
};

// render template
output = ejs.render(template, {
	images: images,
	helpers: helpers
});
// console.log(output);
// write to file
var fs = require('fs');
var filename = require('path').resolve('./', outputScriptName);
fs.writeFileSync(filename, output, {
	encoding: 'utf8'
});
fs.chmodSync(filename, '700');